<?php
/**
 * WARNING: Please do not edit this file in any way
 * load the theme function files
 * Slightly Modified Options Framework
 */
 // Translation
add_action( 'after_setup_theme', 'pixel_load_textdomain' );
function pixel_load_textdomain(){
 load_theme_textdomain( 'pixlin', get_template_directory() . '/languages' );
}
 
 // Default RSS feed links
add_theme_support( 'automatic-feed-links' );

// Default custom header
add_theme_support( 'custom-header' );

// Default custom backgrounds
add_theme_support( 'custom-background' );

// Woocommerce Support
add_theme_support( 'woocommerce' );

// Allow shortcodes in widget text
add_filter('widget_text', 'do_shortcode');

// Default Title Tag
add_theme_support( 'title-tag' );
 
require_once ('admin/index.php');

if ( ! function_exists('pts_get_data') ) {
	function pts_get_data($id, $fallback = false) {
		global $smof_data;
		if ( $fallback == false ) $fallback = '';
		$output = ( isset($smof_data[$id]) && $smof_data[$id] !== '' ) ? $smof_data[$id] : $fallback;
		return $output;
	}
}
require_once( get_template_directory() .'/functions/functions.php' );
require_once( get_template_directory() .'/functions/hooks.php' );
require_once( get_template_directory() .'/functions/function-extras.php' );
//require_once( get_template_directory() .'/functions/custom-css.php' );
//require_once( get_template_directory() .'/functions/tracking.php' );
require_once( get_template_directory() .'/functions/comments-layout.php' );




/************* METABOX ****************/
// Re-define meta box path and URL
//define( 'RWMB_URL', trailingslashit( get_stylesheet_directory_uri() . '/functions/meta-box' ) );
//define( 'RWMB_DIR', trailingslashit( get_template_directory() . '/functions/meta-box' ) );
// Include the meta box script
//require_once RWMB_DIR . 'meta-box.php';
//require_once RWMB_DIR . 'setup.php';




