<?php

$categories = array(
    array('pk_i_id' => 1,   'i_position' => 1,  'fk_i_parent_id' => NULL, 's_name' => __('Продаю')),
    array('pk_i_id' => 2,   'i_position' => 2,  'fk_i_parent_id' => NULL, 's_name' => __('Транспорт')),
    array('pk_i_id' => 3,   'i_position' => 3,  'fk_i_parent_id' => NULL, 's_name' => __('Занятия')),
    array('pk_i_id' => 4,   'i_position' => 4,  'fk_i_parent_id' => NULL, 's_name' => __('Недвижимость')),
    array('pk_i_id' => 5,   'i_position' => 5,  'fk_i_parent_id' => NULL, 's_name' => __('Услуги')),
    array('pk_i_id' => 6,   'i_position' => 6,  'fk_i_parent_id' => NULL, 's_name' => __('Сообщества')),
    array('pk_i_id' => 7,   'i_position' => 7,  'fk_i_parent_id' => NULL, 's_name' => __('Знакомства')),
    array('pk_i_id' => 8,   'i_position' => 8,  'fk_i_parent_id' => NULL, 's_name' => __('Работа')),
    array('pk_i_id' => 9,   'i_position' => 1,  'fk_i_parent_id' => 1,    's_name' => __('Животные')),
    array('pk_i_id' => 10,  'i_position' => 2,  'fk_i_parent_id' => 1,    's_name' => __('Искусство - Коллекционирование')),
    array('pk_i_id' => 11,  'i_position' => 3,  'fk_i_parent_id' => 1,    's_name' => __('Обмен')),
    array('pk_i_id' => 12,  'i_position' => 4,  'fk_i_parent_id' => 1,    's_name' => __('Книги - Журналы')),
    array('pk_i_id' => 13,  'i_position' => 5,  'fk_i_parent_id' => 1,    's_name' => __('Видео камеры - Аксессуары')),
    array('pk_i_id' => 14,  'i_position' => 6,  'fk_i_parent_id' => 1,    's_name' => __('CD диски - Запись')),
    array('pk_i_id' => 15,  'i_position' => 7,  'fk_i_parent_id' => 1,    's_name' => __('Мобильные телефону - Аксессуары')),
    array('pk_i_id' => 16,  'i_position' => 8,  'fk_i_parent_id' => 1,    's_name' => __('Одежда')),
    array('pk_i_id' => 17,  'i_position' => 9,  'fk_i_parent_id' => 1,    's_name' => __('Компьютеры и комплектующие')),
    array('pk_i_id' => 18,  'i_position' => 10, 'fk_i_parent_id' => 1,    's_name' => __('DVD')),
    array('pk_i_id' => 19,  'i_position' => 11, 'fk_i_parent_id' => 1,    's_name' => __('Электроника')),
    array('pk_i_id' => 20,  'i_position' => 12, 'fk_i_parent_id' => 1,    's_name' => __('Детские товары')),
    array('pk_i_id' => 21,  'i_position' => 13, 'fk_i_parent_id' => 1,    's_name' => __('Гаражная распродажа')),
    array('pk_i_id' => 22,  'i_position' => 14, 'fk_i_parent_id' => 1,    's_name' => __('Здоровье и красота')),
    array('pk_i_id' => 23,  'i_position' => 15, 'fk_i_parent_id' => 1,    's_name' => __('Дом - Сад - Огород')),
    array('pk_i_id' => 24,  'i_position' => 16, 'fk_i_parent_id' => 1,    's_name' => __('Ювелирные изделия - Часы')),
    array('pk_i_id' => 25,  'i_position' => 17, 'fk_i_parent_id' => 1,    's_name' => __('Музыкальные инструменты')),
    array('pk_i_id' => 26,  'i_position' => 18, 'fk_i_parent_id' => 1,    's_name' => __('Товары для спорта - велосипеды')),
    array('pk_i_id' => 27,  'i_position' => 19, 'fk_i_parent_id' => 1,    's_name' => __('Билеты')),
    array('pk_i_id' => 28,  'i_position' => 20, 'fk_i_parent_id' => 1,    's_name' => __('Игрушки - Игры - Хобби')),
    array('pk_i_id' => 29,  'i_position' => 21, 'fk_i_parent_id' => 1,    's_name' => __('Видеоигры - Консоли')),
    array('pk_i_id' => 30,  'i_position' => 22, 'fk_i_parent_id' => 1,    's_name' => __('Все остальное')),
    array('pk_i_id' => 31,  'i_position' => 1,  'fk_i_parent_id' => 2,    's_name' => __('Легковые автомобили')),
    array('pk_i_id' => 32,  'i_position' => 2,  'fk_i_parent_id' => 2,    's_name' => __('Автозапчасти')),
    array('pk_i_id' => 33,  'i_position' => 3,  'fk_i_parent_id' => 2,    's_name' => __('Мотоциклы')),
    array('pk_i_id' => 34,  'i_position' => 4,  'fk_i_parent_id' => 2,    's_name' => __('Лодки - Яхты')),
    array('pk_i_id' => 35,  'i_position' => 5,  'fk_i_parent_id' => 2,    's_name' => __('Фургоны - Дома на колесах - Трейлеры')),
    array('pk_i_id' => 36,  'i_position' => 6,  'fk_i_parent_id' => 2,    's_name' => __('Грузовые автомобили - коммерческие автомобили')),
    array('pk_i_id' => 37,  'i_position' => 7,  'fk_i_parent_id' => 2,    's_name' => __('Другие транспортные средства')),
    array('pk_i_id' => 38,  'i_position' => 1,  'fk_i_parent_id' => 3,    's_name' => __('Компьютерные занятия')),
    array('pk_i_id' => 39,  'i_position' => 2,  'fk_i_parent_id' => 3,    's_name' => __('Изучение языков')),
    array('pk_i_id' => 40,  'i_position' => 3,  'fk_i_parent_id' => 3,    's_name' => __('Музыка - Театр - Уроки танцев')),
    array('pk_i_id' => 41,  'i_position' => 4,  'fk_i_parent_id' => 3,    's_name' => __('Репетиторы - Частные уроки')),
    array('pk_i_id' => 42,  'i_position' => 5,  'fk_i_parent_id' => 3,    's_name' => __('Другие курсы и тренинги')),
    array('pk_i_id' => 43,  'i_position' => 1,  'fk_i_parent_id' => 4,    's_name' => __('Дома - Продажа квартир')),
    array('pk_i_id' => 44,  'i_position' => 2,  'fk_i_parent_id' => 4,    's_name' => __('Дома - Аренда квартир, домов')),
    array('pk_i_id' => 45,  'i_position' => 3,  'fk_i_parent_id' => 4,    's_name' => __('Аренда комнат - общежитие')),
    array('pk_i_id' => 46,  'i_position' => 4,  'fk_i_parent_id' => 4,    's_name' => __('Обмен недвижимости')),
    array('pk_i_id' => 47,  'i_position' => 5,  'fk_i_parent_id' => 4,    's_name' => __('Аренда недвижимости на курортах')),
    array('pk_i_id' => 48,  'i_position' => 6,  'fk_i_parent_id' => 4,    's_name' => __('Гаражи, стоянки')),
    array('pk_i_id' => 49,  'i_position' => 7,  'fk_i_parent_id' => 4,    's_name' => __('Земля')),
    array('pk_i_id' => 50,  'i_position' => 8,  'fk_i_parent_id' => 4,    's_name' => __('Офисы - Коммерческие помещения')),
    array('pk_i_id' => 51,  'i_position' => 9,  'fk_i_parent_id' => 4,    's_name' => __('Аренда и продажа магазинов - Прочие')),
    array('pk_i_id' => 52,  'i_position' => 1,  'fk_i_parent_id' => 5,    's_name' => __('Няни - Домоработницы')),
    array('pk_i_id' => 53,  'i_position' => 2,  'fk_i_parent_id' => 5,    's_name' => __('Кастинг - Прослушивание')),
    array('pk_i_id' => 54,  'i_position' => 3,  'fk_i_parent_id' => 5,    's_name' => __('Компьютер')),
    array('pk_i_id' => 55,  'i_position' => 4,  'fk_i_parent_id' => 5,    's_name' => __('Прочие услуги')),
    array('pk_i_id' => 56,  'i_position' => 5,  'fk_i_parent_id' => 5,    's_name' => __('Здоровье - Красота - Фитнес')),
    array('pk_i_id' => 57,  'i_position' => 6,  'fk_i_parent_id' => 5,    's_name' => __('Гороскопы - Таро')),
    array('pk_i_id' => 58,  'i_position' => 7,  'fk_i_parent_id' => 5,    's_name' => __('Хозяйство - Помощь по дому')),
    array('pk_i_id' => 59,  'i_position' => 8,  'fk_i_parent_id' => 5,    's_name' => __('Перемещение - Хранение')),
    array('pk_i_id' => 60,  'i_position' => 9,  'fk_i_parent_id' => 5,    's_name' => __('Ремонт')),
    array('pk_i_id' => 61,  'i_position' => 10, 'fk_i_parent_id' => 5,    's_name' => __('Запись - Редактирование - Перевод')),
    array('pk_i_id' => 62,  'i_position' => 11, 'fk_i_parent_id' => 5,    's_name' => __('Прочие услуги')),
    array('pk_i_id' => 63,  'i_position' => 1,  'fk_i_parent_id' => 6,    's_name' => __('Ищу попутчика')),
    array('pk_i_id' => 64,  'i_position' => 2,  'fk_i_parent_id' => 6,    's_name' => __('Общественная деятельность')),
    array('pk_i_id' => 65,  'i_position' => 3,  'fk_i_parent_id' => 6,    's_name' => __('События')),
    array('pk_i_id' => 66,  'i_position' => 4,  'fk_i_parent_id' => 6,    's_name' => __('Музыканты - Художники - Группы')),
    array('pk_i_id' => 67,  'i_position' => 5,  'fk_i_parent_id' => 6,    's_name' => __('Волонтеры')),
    array('pk_i_id' => 68,  'i_position' => 6,  'fk_i_parent_id' => 6,    's_name' => __('Бюро находок')),
    array('pk_i_id' => 69,  'i_position' => 1,  'fk_i_parent_id' => 7,    's_name' => __('Она ищет его')),
    array('pk_i_id' => 70,  'i_position' => 2,  'fk_i_parent_id' => 7,    's_name' => __('Он ищет ее')),
    array('pk_i_id' => 71,  'i_position' => 3,  'fk_i_parent_id' => 7,    's_name' => __('Он ищет его')),
    array('pk_i_id' => 72,  'i_position' => 4,  'fk_i_parent_id' => 7,    's_name' => __('Она ищет ее')),
    array('pk_i_id' => 73,  'i_position' => 5,  'fk_i_parent_id' => 7,    's_name' => __('Дружба - Деятельность - Партнеры')),
    array('pk_i_id' => 74,  'i_position' => 6,  'fk_i_parent_id' => 7,    's_name' => __('Потерянные связи')),
    array('pk_i_id' => 75,  'i_position' => 1,  'fk_i_parent_id' => 8,    's_name' => __('Бухгалтерский учет - Финансы')),
    array('pk_i_id' => 76,  'i_position' => 2,  'fk_i_parent_id' => 8,    's_name' => __('Реклама - Связи с общественностью')),
    array('pk_i_id' => 77,  'i_position' => 3,  'fk_i_parent_id' => 8,    's_name' => __('Искусство - Развлечения - Издания')),
    array('pk_i_id' => 78,  'i_position' => 4,  'fk_i_parent_id' => 8,    's_name' => __('Канцелярия - Администрация')),
    array('pk_i_id' => 79,  'i_position' => 5,  'fk_i_parent_id' => 8,    's_name' => __('Сервисные службы')),
    array('pk_i_id' => 80,  'i_position' => 6,  'fk_i_parent_id' => 8,    's_name' => __('Образование - Обучение')),
    array('pk_i_id' => 81,  'i_position' => 7,  'fk_i_parent_id' => 8,    's_name' => __('Инженерия - Архитектура')),
    array('pk_i_id' => 82,  'i_position' => 8,  'fk_i_parent_id' => 8,    's_name' => __('Здоровье')),
    array('pk_i_id' => 83,  'i_position' => 9,  'fk_i_parent_id' => 8,    's_name' => __('Человеческие ресурсы')),
    array('pk_i_id' => 84,  'i_position' => 10, 'fk_i_parent_id' => 8,    's_name' => __('Итернет')),
    array('pk_i_id' => 85,  'i_position' => 11, 'fk_i_parent_id' => 8,    's_name' => __('Право')),
    array('pk_i_id' => 86,  'i_position' => 12, 'fk_i_parent_id' => 8,    's_name' => __('Физический труд')),
    array('pk_i_id' => 87,  'i_position' => 13, 'fk_i_parent_id' => 8,    's_name' => __('Производство - Фабрики')),
    array('pk_i_id' => 88,  'i_position' => 14, 'fk_i_parent_id' => 8,    's_name' => __('Маркетинг')),
    array('pk_i_id' => 89,  'i_position' => 15, 'fk_i_parent_id' => 8,    's_name' => __('Некоммерческие организации - Волонтеры')),
    array('pk_i_id' => 90,  'i_position' => 16, 'fk_i_parent_id' => 8,    's_name' => __('Недвижимость')),
    array('pk_i_id' => 91,  'i_position' => 17, 'fk_i_parent_id' => 8,    's_name' => __('Рестораны - Быстрое питание')),
    array('pk_i_id' => 92,  'i_position' => 18, 'fk_i_parent_id' => 8,    's_name' => __('Розничная торговля')),
    array('pk_i_id' => 93,  'i_position' => 19, 'fk_i_parent_id' => 8,    's_name' => __('Продажа')),
    array('pk_i_id' => 94,  'i_position' => 20, 'fk_i_parent_id' => 8,    's_name' => __('Технологии')),
    array('pk_i_id' => 95,  'i_position' => 21, 'fk_i_parent_id' => 8,    's_name' => __('Прочие сферы деятельности'))
);


$item = array(
    'catId' => 9,
    'title' => __('Пример объявления'),
    'description' => __('Описание примера объявления. Здесь должно быть описание вашего объявления, развернутое.'),
    'contactName' => __('Пример автора'),
    'contactEmail' => __('osclass@example.com'),
    'country' => __('Пример страна'),
    'region' => __('Пример регион'),
    'city' => __('Пример город'),
);


$page = array(
    's_title' => __('Заголовок примера страницы'),
    's_text' => __('Это описание примера страницы. На данной странице вы можете написать об условиях предоставления услуг или любой другой справочной информации.'),
    's_internal_name' => 'example_page'
);

// EOF: ./oc-includes/osclass/installer/basic_data.php